### ISSUE TITLE
Is it possible to use RepoParser to get the x, y, z and island of a npc neuitem?

### ISSUE THREAD

**Issue by InkEcau** [NotEnoughUpdates/RepoParser#1]
like this
```java
package io.github.moulberry.repo.data;
public class NEUItem {
// ...
int x;
int y;
int z;
String island;
// ...
}
```

**Comment by lineargraph** [comment]
Not a thing right now, but this is something that should be added. Ideally I could've made this easier on you by just providing a `Map` with not parsed data, but this is something that gson sadly does not support out of the box.
